# **3.Pandas Library**

In [ ]:
import pandas as pd
import numpy as np

## **Creating Dataframe**

In [ ]:
employee={"Employee":["Alice","Bob","Charlie","David"], "Department":["Finance","HR","IT","Sales"],"Salary":[60000,50000,70000,55000]}
df=pd.DataFrame(employee)
df

## **Inspecting Data**

In [ ]:
display(df.head())
display(df.head(2))

In [ ]:
display(df.tail())
display(df.tail(2))

In [ ]:
df.shape

(6, 4)

In [ ]:
df.columns

Index(['Name', 'Department', 'Salary', 'Annual Salary'], dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Name           6 non-null      object
 1   Department     6 non-null      object
 2   Salary         6 non-null      int64
 3   Annual Salary  6 non-null      int64
dtypes: int64(2), object(2)
memory usage: 324.0+ bytes

In [ ]:
display(df.describe()) #numerical summary
print("\n")
display(df.describe(include="all")) #summary all
print("\n")
display(df.describe(include="object")) #categorical/text summary

             Salary  Annual Salary
count      6.000000       6.000000
mean   65833.333333  790000.000000
std     9174.239296  110090.871556
min    55000.000000  660000.000000
25%    57500.000000  690000.000000
50%    67500.000000  810000.000000
75%    73750.000000  885000.000000
max    75000.000000  900000.000000

         Name Department        Salary  Annual Salary
count       6          6      6.000000       6.000000
unique      6          3           NaN            NaN
top     Alice    Finance           NaN            NaN
freq        1          3           NaN            NaN
mean      NaN        NaN  65833.333333  790000.000000
std       NaN        NaN   9174.239296  110090.871556
min       NaN        NaN  55000.000000  660000.000000
25%       NaN        NaN  57500.000000  690000.000000
50%       NaN        NaN  67500.000000  810000.000000
75%       NaN        NaN  73750.000000  885000.000000
max       NaN        NaN  75000.000000  900000.000000

         Name Department
count       6          6
unique      6          3
top     Alice    Finance
freq        1          3

In [ ]:
display(df.memory_usage()) #to check memory
display(df.memory_usage().sum()) #total memory
display(df.memory_usage(deep=True).sum()) #total memory inc. object/str data [for mb use "/(1024**2)"]

Index            132
Name              48
Department        48
Salary            48
Annual Salary     48
dtype: int64

np.int64(324)

np.int64(871)

In [ ]:
pd.set_option("display.max_columns",None) # to disable truncation of cols

In [ ]:
df.sample(5) #random 5 rows

In [ ]:
df.nunique() #unique values

NameError: name 'df' is not defined

## **Selecting Columns**

In [ ]:
display(df["Salary"])
display(df["Department"])
display(df[["Employee","Salary"]])
display(df[["Department","Salary"]])

## **Selecting Rows**

In [ ]:
# iloc(Integer Location) - use for row & column number(only index postions)

display(df.iloc[0])
display(df.iloc[:2])
print(df.iloc[1,2])
display(df.iloc[:2,:2])

In [ ]:
# loc(Location) - use for row name & column name(can use if index number is changed)


display(df.loc[0])
display(df.loc[:2])
print("\n")
print(df.loc[1,"Salary"])     # need to type the column names
display(df.loc[:2,["Employee","Department"]])     # here 2 is included

Name               Alice
Department       Finance
Salary             65000
Annual Salary     780000
Name: 0, dtype: object

    Name Department  Salary  Annual Salary
0  Alice    Finance   65000         780000
1   John    Finance   55000         660000
2    Bob         HR   55000         660000

55000

KeyError: "['Employee'] not in index"

## **Filtering Rows**

In [ ]:
df[df["Salary"]>55000]

In [ ]:
df[df["Department"]=="Sales"]

In [ ]:
df[(df["Salary"]<=55000)]

In [ ]:
df[(df["Department"]=="Finance") | (df["Department"]=="IT")]

In [ ]:
df[(df["Department"]=="Finance") & (df["Salary"]>55000)]

## **Sorting Data (sort_values())**

In [ ]:
df.sort_values("Salary")

In [ ]:
df.sort_values("Salary",ascending=False)

In [ ]:
df.sort_values("Department")

In [ ]:
# Sample datset for multiple columns

employee = {
    "Employee": ["Alice","John","Bob","Charlie","David","Emma"],
    "Department": ["Finance","Finance","HR","IT","Finance","HR"],
    "Salary": [60000,50000,50000,70000,70000,65000]
}

df = pd.DataFrame(employee)

In [ ]:
df.sort_values(["Department","Salary"])

      Name Department  Salary  Annual Salary
1     John    Finance   55000         660000
0    Alice    Finance   65000         780000
4    David    Finance   75000         900000
2      Bob         HR   55000         660000
5     Emma         HR   70000         840000
3  Charlie         IT   75000         900000

## **Adding & Modifying Columns**

In [ ]:
df["Salary"]=df["Salary"]+5000

In [ ]:
df["Bonus"]=df["Salary"]*1.10

In [ ]:
df["Country"]="India"

In [ ]:
df["High Salary"]=df["Salary"]>60000

In [ ]:
df["Annual Salary"]=df["Salary"]*12

In [ ]:
df

## **Dropping & Renaming Columns**

In [ ]:
df=df.drop(columns="Country")

In [ ]:
df=df.drop(columns=["Bonus","High Salary"])

In [ ]:
df=df.rename(columns={"Employee":"Name"})

In [ ]:
df

## **Missing Values**

### **Dataset**

In [ ]:
# Sample dataset for missing values

import numpy as np
employee1 = {
    "Employee": ["Alice", "Bob", "Charlie", "David"],
    "Department": ["Finance", "HR", "IT", np.nan],
    "Salary": [60000, np.nan, 70000, 55000]
}

df3 = pd.DataFrame(employee1)

### **Code**

In [ ]:
df3.isna()

In [ ]:
df3.isna().sum()

Employee      0
Department    1
Salary        0
dtype: int64

In [ ]:
df3.isna().sum().idxmax()  # to return column name of highest no of missing values

## **Handling Missing Values**

In [ ]:
df3.dropna() # drop the rows with NaN

  Employee Department   Salary
0    Alice    Finance  60000.0
1      Bob         HR  61667.0
2  Charlie         IT  70000.0

In [ ]:
df3.fillna("Unknown")

  Employee Department   Salary
0    Alice    Finance  60000.0
1      Bob         HR  61667.0
2  Charlie         IT  70000.0
3    David    Unknown  55000.0

In [ ]:
df3["Salary"] = df3["Salary"].fillna(0)
df3

  Employee Department   Salary
0    Alice    Finance  60000.0
1      Bob         HR  61667.0
2  Charlie         IT  70000.0
3    David        NaN  55000.0

In [ ]:
employee2 = {
    "Employee": ["Alice", "Bob", "Charlie", "David"],
    "Department": ["Finance", "HR", "IT", np.nan],
    "Salary": [60000, np.nan, 70000, 55000]
}

df3 = pd.DataFrame(employee2)

df3["Salary"] = df3["Salary"].fillna(round(df3["Salary"].mean()))

In [ ]:
df3

  Employee Department   Salary
0    Alice    Finance  60000.0
1      Bob         HR  61667.0
2  Charlie         IT  70000.0
3    David        NaN  55000.0

## **GroupBy**

### **Dataset**

In [ ]:
import pandas as pd

employee_data = {
    "Employee": ["Alice", "John", "Bob", "Charlie", "David", "Emma", "Kevin", "Sophia"],
    "Department": ["Finance", "Finance", "HR", "IT", "Finance", "HR", "IT", "Finance"],
    "Gender": ["Female", "Male", "Male", "Male", "Male", "Female", "Male", "Female"],
    "Salary": [60000, 50000, 50000, 70000, 70000, 65000, 75000, 80000]
}

emp_df = pd.DataFrame(employee_data)

### **Code**

In [ ]:
emp_df.groupby("Department")["Salary"].mean()

In [ ]:
emp_df.groupby("Department")["Salary"].sum()

In [ ]:
emp_df.groupby("Department")["Employee"].count()

In [ ]:
emp_df.groupby("Department")["Salary"].agg(["mean","sum","min","max","count"])

In [ ]:
emp_df.groupby(["Department","Gender"])["Salary"].agg("mean")

## **Merging DataFrames (merge())**

### **Datasets**

In [ ]:
employees={
    "EmployeeID":[101,102,103,104],
    "Name":["Alice","Bob","charlie","David"],
    "DepartmentID":[1,2,1,3]
    }
empl_df=pd.DataFrame(employees)

In [ ]:
departments = {
    "DepartmentID": [1,2,3],
    "Department": ["Finance","HR","IT"]
}

dep_df = pd.DataFrame(departments)

### **Code**

In [ ]:
pd.merge(empl_df,dep_df,on="DepartmentID")

In [ ]:
pd.merge(empl_df,dep_df,on="DepartmentID",how="left")

In [ ]:
pd.merge(empl_df,dep_df,on="DepartmentID",how="outer")

## **Pivot Tables**

### **Dataset**

In [ ]:
sales_data = {
    "Region": ["North","North","North","South","South","South","East","East","West","West"],
    "Category": ["Electronics","Furniture","Electronics","Furniture","Electronics","Furniture","Electronics","Furniture","Electronics","Furniture"],
    "Salesperson": ["Alice","Bob","Alice","Charlie","David","Charlie","Emma","Emma","Frank","Frank"],
    "Gender": ["F","M","F","M","M","M","F","F","M","M"],
    "Sales": [5000,3000,7000,4000,6000,3500,8000,4500,9000,5000],
    "Profit": [1000,500,1800,700,1200,600,2000,900,2500,1000]
}

sales_df = pd.DataFrame(sales_data)

sales_df

### **Code**

In [ ]:
pd.pivot_table(sales_df,index="Region",values="Sales",aggfunc="mean")

         Sales
Region
East    6250.0
North   5000.0
South   4500.0
West    7000.0

In [ ]:
pd.pivot_table(sales_df,index="Category",values="Profit",aggfunc="sum")

             Profit
Category
Electronics    8500
Furniture      3700

In [ ]:
pd.pivot_table(sales_df,
               index="Region"
               ,columns="Category"
               ,values="Sales"
               ,aggfunc="sum",
               sort = False  # to make table not to sort
)

Category  Electronics  Furniture
Region
North           12000       3000
South            6000       7500
East             8000       4500
West             9000       5000

In [ ]:
pd.pivot_table(sales_df,
               index=["Region","Category"],
               columns="Gender",
               values="Sales",
               aggfunc="mean",
               dropna=False,) # used when an entire NaN column is needed(actually deletes automatically if so)

Gender                   F       M
Region Category
East   Electronics  8000.0     NaN
       Furniture    4500.0     NaN
North  Electronics  6000.0     NaN
       Furniture       NaN  3000.0
South  Electronics     NaN  6000.0
       Furniture       NaN  3750.0
West   Electronics     NaN  9000.0
       Furniture       NaN  5000.0

In [ ]:
pivot=pd.pivot_table(sales_df,index="Region",values=["Sales","Profit"],aggfunc="mean")

pivot.rename(columns={"Profit":"Avg Profit","Sales":"Avg Sales"})

         Avg Profit  Avg Sales
Region
East    1450.000000     6250.0
North   1100.000000     5000.0
South    833.333333     4500.0
West    1750.000000     7000.0

In [ ]:
pd.pivot_table(sales_df,
               index="Region",
               values="Sales",
               aggfunc=["mean","sum","count","max"],
               margins=True, margins_name="Grand Total") #grand total[for mean it gives overall avg]

               mean    sum count   max
              Sales  Sales Sales Sales
Region
East         6250.0  12500     2  8000
North        5000.0  15000     3  7000
South        4500.0  13500     3  6000
West         7000.0  14000     2  9000
Grand Total  5500.0  55000    10  9000

In [ ]:
pivot1=pd.pivot_table(sales_df,
               index=["Region","Category"],
               columns="Gender",values=["Sales","Profit"],
               aggfunc=["mean","sum"],
               fill_value=0,  #filling Nan with 0
               )
pivot1.columns=["_".join(map(str,col))    # used for Flattening MultiIndex columns(rename)
                for col in pivot1.columns
]
display(pivot1)

                    mean_Profit_F  mean_Profit_M  mean_Sales_F  mean_Sales_M  \
Region Category
East   Electronics         2000.0            0.0        8000.0           0.0
       Furniture            900.0            0.0        4500.0           0.0
North  Electronics         1400.0            0.0        6000.0           0.0
       Furniture              0.0          500.0           0.0        3000.0
South  Electronics            0.0         1200.0           0.0        6000.0
       Furniture              0.0          650.0           0.0        3750.0
West   Electronics            0.0         2500.0           0.0        9000.0
       Furniture              0.0         1000.0           0.0        5000.0

                    sum_Profit_F  sum_Profit_M  sum_Sales_F  sum_Sales_M
Region Category
East   Electronics          2000             0         8000            0
       Furniture             900             0         4500            0
North  Electronics          2800             0        12000            0
       Furniture               0           500            0         3000
South  Electronics             0          1200            0         6000
       Furniture               0          1300            0         7500
West   Electronics             0          2500            0         9000
       Furniture               0          1000            0         5000

In [ ]:
# Different aggregation for each value column
pd.pivot_table(
    sales_df,
    index="Region",
    values=["Sales", "Profit"],
    aggfunc={
        "Sales": "mean",
        "Profit": "sum"
    }
)

        Profit   Sales
Region
East      2900  6250.0
North     3300  5000.0
South     2500  4500.0
West      3500  7000.0

## **String Operations (.str)**

### **Dataset**

In [ ]:
import pandas as pd

employee_data = {
    "Employee": [
        " alice ",
        "BOB",
        "charLie",
        " DAVID ",
        " emma ",
        "John Doe",
        "SARA ALI",
        "  kevin joseph  ",
        "michael smith",
        " ANNA "
    ],

    "Department": [
        "finance",
        " HR ",
        "it",
        "Finance",
        " hr ",
        "IT",
        "FINANCE",
        "sales ",
        " Marketing",
        "finance "
    ],

    "Email": [
        "alice@gmail.com",
        "BOB@GMAIL.COM",
        "charlie@yahoo.com",
        " david@hotmail.com ",
        "emma@gmail.com",
        "john.doe@gmail.com",
        "SARA@YAHOO.COM",
        " kevin@gmail.com ",
        "michael@outlook.com",
        " ANNA@GMAIL.COM "
    ],

    "Employee ID":[
        "EMP101",
        "EMP102",
        "EMP103",
        "EMP104",
        "EMP105",
        "EMP106",
        "EMP107",
        "EMP108",
        "EMP109",
        "EMP110"
    ]
}

e_df = pd.DataFrame(employee_data)

e_df

### **Code**

In [ ]:
e_df["Employee"].str.upper() #uppercase

In [ ]:
e_df["Employee"].str.lower() #lowercase

In [ ]:
e_df["Employee"].str.title() #first letter of words caps

In [ ]:
e_df["Employee"].str.strip().str.capitalize() #to caps 1st letter

In [ ]:
e_df[["Employee","Email","Department"]]=(
    e_df[["Employee","Email","Department"]]
    .apply(lambda col: col.str.strip())  #strip for multiple columns
    )
display(e_df)

In [ ]:
e_df["Employee"].str.contains("a",case=False) #contains- ignoring case

In [ ]:
e_df["Email"].str.lower().str.contains("gmail",case=False) #contains - ignoring case

In [ ]:
e_df["Employee"].str.lower().str.startswith("a") #startswith - use lower or upper(to ignore case)

In [ ]:
e_df["Email"].str.lower().str.endswith(".com") #endswith [same as startswith]

In [ ]:
e_df["Department"]=e_df["Department"].str.strip().str.upper().str.replace("FINANCE","ACCOUNTS")
e_df # to replace values - use upper/lower before that

In [ ]:
e_df["Employee"].str.len() # length

In [ ]:
e_df["Length"]=e_df["Employee"].str.len() #create temp column with length
e_df.loc[e_df["Length"].idxmax()] #use np fn(idxmax) to get the row of max-(use "name" to get only max name)

In [ ]:
e_df["Employee"].str.split(" ") #to split it as list

In [ ]:
e_df[['First Name','Last Name']]=e_df["Employee"].str.split(" ",expand=True) # to split first, last name (expand for columns)
e_df["Last Name"]=e_df["Last Name"].fillna("") # to fill Nan with "" (blank)
e_df

In [ ]:
display(e_df["Employee"].str[:3], #slicing
        e_df["Employee"].str.slice(0,3) #slicing with slice fn
        )

In [ ]:
e_df["Employee"].str.lower().str.count("a") #to count (use same case-upper/lower to ignore case)

In [ ]:
e_df["Employee ID"].str.extract(r'(\d+)') #extract to get particular part of col as newcol (refer the code letters)

In [ ]:
e_df["Employee Info"]=e_df["Employee"].str.cat(e_df["Department"],sep=" - ") #concat
e_df

In [ ]:
display(e_df["Employee"].str.split().str.get(0),e_df["Employee"].str.split().str.get(1)) #geting the element after splitting

## **Date & Time Handling**

### **Dataset**

In [ ]:
import pandas as pd

orders_data = {
    "Order ID": [101,102,103,104,105,106],
    "Customer": ["Alice","Bob","Charlie","David","Emma","Frank"],
    "Order Date": [
        "2025-01-15",
        "2025-02-20",
        "2025-03-12",
        "2025-03-25",
        "2025-04-18",
        "2025-05-01"
    ],
    "Sales":[2500,1800,3200,1500,4100,2800]
}

orders_df = pd.DataFrame(orders_data)

orders_df
display(orders_df.info()) #it is a string not date

### **Code**

In [ ]:
orders_df["Order Date"]=pd.to_datetime(orders_df["Order Date"]) #converted to date
orders_df.info()

In [ ]:
orders_df["Year"]=orders_df["Order Date"].dt.year
orders_df

In [ ]:
orders_df["Month"]=orders_df["Order Date"].dt.month_name()
orders_df

In [ ]:
orders_df["Day"]=orders_df["Order Date"].dt.day
orders_df

In [ ]:
orders_df["Weekday"]=orders_df["Order Date"].dt.day_name()
orders_df

In [ ]:
orders_df["Order Date"][orders_df["Order Date"]>"2025-03-01"]

In [ ]:
orders_df["Order Date"][orders_df["Order Date"].dt.month==3] # can also use orders_df.loc returning order date at last

In [ ]:
orders_df["Quarter"]=orders_df["Order Date"].dt.quarter

In [ ]:
orders_df["Is Weekend"]=(orders_df["Order Date"].dt.dayofweek>5)

In [ ]:
orders_df["Delivery Date"] = [
    "2025-01-18",
    "2025-02-25",
    "2025-03-15",
    "2025-03-29",
    "2025-04-25",
    "2025-05-05"
]

orders_df["Delivery Date"]=pd.to_datetime(orders_df["Delivery Date"])

In [ ]:
orders_df["Delivery Days"]=(orders_df["Delivery Date"]-orders_df["Order Date"]).dt.days

In [ ]:
orders_df["Order Date"]=orders_df["Order Date"].dt.strftime("%d-%b-%Y") #string format to time

In [ ]:
orders_df["Order Date"]=pd.to_datetime(orders_df["Order Date"])

orders_df.groupby(orders_df["Order Date"].dt.month_name())["Sales"].sum().sort_values(ascending=False)

Order Date
March       4700
April       4100
May         2800
January     2500
February    1800
Name: Sales, dtype: int64

## **map(), apply(), and lambda**

### map()

### **Dataset**

In [ ]:
student_data = {
    "Student":["Ram","John","Sara","Emma","Alex"],
    "Gender":["M","M","F","F","M"],
    "Result":["P","F","P","P","F"]
}

student_df = pd.DataFrame(student_data)
student_df2 = student_df.copy() #because once it maps then old one is deleted

### **Code**

In [ ]:
student_df2["Gender"]=student_df2["Gender"].map({"M":"Male","F":"Female"})

In [ ]:
student_df2["Result"]=student_df2["Result"].map({"P":"Pass","F":"Fail"})

In [ ]:
student_df2["Scholarship"]=student_df2["Result"].map({"Pass":"Eligible","Fail":"Not Eligible"})
student_df2

### apply()

### **Dataset**

In [ ]:
# apply()

student_data = {
    "Student":["Ram","John","Sara","Emma","Alex"],
    "Marks":[95,72,35,88,40]
}

student_df = pd.DataFrame(student_data)

### **Code**

In [ ]:
def result(Marks):
  if Marks >=40:
    return "Pass"
  else:
    return "Fail"

student_df["Result"]=student_df["Marks"].apply(result)
student_df

  Student  Marks Result
0     Ram     95   Pass
1    John     72   Pass
2    Sara     35   Fail
3    Emma     88   Pass
4    Alex     40   Pass

In [ ]:
def grade(Marks):
  if Marks>=90:
    return "A"
  elif Marks >=75 and Marks<90:
    return "B"
  elif Marks>=40 and Marks<75:
    return "C"
  else:
    return "D"

student_df["Grade"]=student_df["Marks"].apply(grade)
student_df

In [ ]:
def b_mark(Marks):
  if Marks>=95: #capped to 100
    return 100
  else:
    return Marks+5

student_df["Bonus Marks"]=student_df["Marks"].apply(b_mark)
student_df

### lambda

### **Code**

In [ ]:
x=16

print("Value: ",(lambda x : x*2)(x))

print("Odd/Even: ",(lambda x:"Even" if x%2==0 else "Odd")(x))

print("Adult/Child: ",(lambda x: "Adult" if x>=18 else "Child")(x))

### apply() + lambda

### **Dataset**

In [ ]:
student_data = {
    "Student":["Ram","John","Sara","Emma"],
    "Marks":[95,85,38,72],
    "Attendance":[92,60,95,80]
}

student_df = pd.DataFrame(student_data)

### **Code**

In [ ]:
student_df["Double Marks"]=student_df["Marks"].apply(lambda x:x*2) #just for practice purpose
student_df

In [ ]:
student_df["Result"]=student_df["Marks"].apply(lambda x: "Pass" if x >=40 else "Fail")
student_df

In [ ]:
student_df["Bonus Marks"]=student_df["Marks"].apply(lambda x: 100 if x>=95 else x+5)
student_df

In [ ]:
student_df["Final Result"]=student_df.apply(lambda row:
                                            "Pass" if row["Marks"]>=40 and row["Attendance"]>=75
                                            else "Fail",
                                            axis=1 #row wise(0 for column)
                                            )
student_df

In [ ]:
student_df["Grade"]=student_df.apply(lambda row:
                                     "F" if row["Marks"]<40
                                     else
                                     "A" if row["Marks"]>=90 and  row["Attendance"]>=90
                                     else
                                     "B" if row["Marks"]>=75
                                     else "C",
                                     axis=1
                                     )
student_df

## **Reading Data Sources (Reference-Not Workable)**

### **CSV**

In [ ]:
import pandas as pd

df=pd.read_csv("employees.csv")

In [ ]:
pd.read_csv("employees.csv",usecols=["Employee","Salary"]) #to use specific cols

In [ ]:
pd.read_csv("employees.csv",nrows=10) #to select n rows for testing

In [ ]:
pd.read_csv("employees.csv",skiprows=[1,2,3]) #to skip rows

In [ ]:
pd.read_csv("employees.csv",sep=";") #delimiter to ;

In [ ]:
pd.read_csv("employees.csv",index_col="Employee") #to make col(employee here) as index

In [ ]:
pd.read_csv("employees.csv",na_values=["NA","Missing","--"]) # to change misssing values to Nan

In [ ]:
df.to_csv("cleaned.csv", index=False) #to save as csv

### **Excel**

In [ ]:
df=pd.read_excel("employees.xlsx")

In [ ]:
pd.read_excel("employees.xlsx",sheet_name="Sales") #to select particular sheet name from workbook

d.read_excel("employees.xlsx",sheet_name=1) #can also use col number

In [ ]:
pd.read_excel("employees.xlsx", usecols=["Employee","Salary"]) #to read selective cols

In [ ]:
pd.read_excel("employees.xlsx",nrows=10) #to read n rows

pd.read_excel("employees.xlsx",skiprows=10) #to skip rows

In [ ]:
df.to_excel("cleaned.xlsx",index=False) # to save as excel

### **SQL**

In [ ]:
from sqlalchemy import create_engine #to import sql lib

In [ ]:
engine=create_engine("database_connection_string") #to set up connection

In [ ]:
df=pd.read_sql("Select * from employees",engine) #to read all data

In [ ]:
querry="""select department, avg(salary) from employees group by department"""

df=pd.read_sql(querry,engine) #to read sql querry

In [ ]:
df.to_sql('employees',engine,if_exists='replace',index=False) #to save as sql(if exists - replace(fail,append))

## **Data Analysis Workflow**

1. CSV / Excel / SQL / API
2. Read into pandas
3. EDA
4. Cleaning
5. Analysis
6. Visualise
7. Export (CSV / Excel / SQL)