# **3.Pandas Library**

In [4]:
import pandas as pd
import numpy as np

## **Creating Dataframe**

In [ ]:
employee={"Employee":["Alice","Bob","Charlie","David"], "Department":["Finance","HR","IT","Sales"],"Salary":[60000,50000,70000,55000]}
df=pd.DataFrame(employee)
df

  Employee Department  Salary
0    Alice    Finance   60000
1      Bob         HR   50000
2  Charlie         IT   70000
3    David      Sales   55000

## **Inspecting Data**

In [ ]:
display(df.head())
display(df.head(2))

  Employee Department  Salary
0    Alice    Finance   60000
1      Bob         HR   50000
2  Charlie         IT   70000
3    David      Sales   55000

  Employee Department  Salary
0    Alice    Finance   60000
1      Bob         HR   50000

In [ ]:
display(df.tail())
display(df.tail(2))

  Employee Department  Salary
0    Alice    Finance   60000
1      Bob         HR   50000
2  Charlie         IT   70000
3    David      Sales   55000

  Employee Department  Salary
2  Charlie         IT   70000
3    David      Sales   55000

In [ ]:
df.shape

(4, 3)

In [ ]:
df.columns

Index(['Employee', 'Department', 'Salary'], dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Employee    4 non-null      object
 1   Department  4 non-null      object
 2   Salary      4 non-null      int64
dtypes: int64(1), object(2)
memory usage: 228.0+ bytes

## **Selecting Columns**

In [ ]:
display(df["Salary"])
display(df["Department"])
display(df[["Employee","Salary"]])
display(df[["Department","Salary"]])

0    60000
1    50000
2    70000
3    55000
Name: Salary, dtype: int64

0    Finance
1         HR
2         IT
3      Sales
Name: Department, dtype: object

  Employee  Salary
0    Alice   60000
1      Bob   50000
2  Charlie   70000
3    David   55000

  Department  Salary
0    Finance   60000
1         HR   50000
2         IT   70000
3      Sales   55000

## **Selecting Rows**

In [ ]:
# iloc(Integer Location) - use for row & column number(only index postions)

display(df.iloc[0])
display(df.iloc[:2])
print(df.iloc[1,2])
display(df.iloc[:2,:2])

Employee        Alice
Department    Finance
Salary          60000
Name: 0, dtype: object

  Employee Department  Salary
0    Alice    Finance   60000
1      Bob         HR   50000

50000

  Employee Department
0    Alice    Finance
1      Bob         HR

In [ ]:
# loc(Location) - use for row name & column name(can use if index number is changed)


display(df.loc[0])
display(df.loc[:2])
print("\n")
print(df.loc[1,"Salary"])     # need to type the column names
display(df.loc[:2,["Employee","Department"]])     # here 2 is included

Employee        Alice
Department    Finance
Salary          60000
Name: 0, dtype: object

  Employee Department  Salary
0    Alice    Finance   60000
1      Bob         HR   50000
2  Charlie         IT   70000

50000

  Employee Department
0    Alice    Finance
1      Bob         HR
2  Charlie         IT

## **Filtering Rows**

In [ ]:
df[df["Salary"]>55000]

  Employee Department  Salary
0    Alice    Finance   60000
2  Charlie         IT   70000

In [ ]:
df[df["Department"]=="Sales"]

  Employee Department  Salary
3    David      Sales   55000

In [ ]:
df[(df["Salary"]<=55000)]

  Employee Department  Salary
1      Bob         HR   50000
3    David      Sales   55000

In [ ]:
df[(df["Department"]=="Finance") | (df["Department"]=="IT")]

  Employee Department  Salary
0    Alice    Finance   60000
2  Charlie         IT   70000

In [ ]:
df[(df["Department"]=="Finance") & (df["Salary"]>55000)]

  Employee Department  Salary
0    Alice    Finance   60000

## **Sorting Data (sort_values())**

In [ ]:
df.sort_values("Salary")

  Employee Department  Salary
1      Bob         HR   50000
3    David      Sales   55000
0    Alice    Finance   60000
2  Charlie         IT   70000

In [ ]:
df.sort_values("Salary",ascending=False)

  Employee Department  Salary
2  Charlie         IT   70000
0    Alice    Finance   60000
3    David      Sales   55000
1      Bob         HR   50000

In [ ]:
df.sort_values("Department")

  Employee Department  Salary
0    Alice    Finance   60000
1      Bob         HR   50000
2  Charlie         IT   70000
3    David      Sales   55000

In [6]:
# Sample datset for multiple columns

employee = {
    "Employee": ["Alice","John","Bob","Charlie","David","Emma"],
    "Department": ["Finance","Finance","HR","IT","Finance","HR"],
    "Salary": [60000,50000,50000,70000,70000,65000]
}

df = pd.DataFrame(employee)

In [7]:
df.sort_values(["Department","Salary"])

  Employee Department  Salary
1     John    Finance   50000
0    Alice    Finance   60000
4    David    Finance   70000
2      Bob         HR   50000
5     Emma         HR   65000
3  Charlie         IT   70000

## **Adding & Modifying Columns**

In [ ]:
df["Salary"]=df["Salary"]+5000

In [ ]:
df["Bonus"]=df["Salary"]*1.10

In [ ]:
df["Country"]="India"

In [ ]:
df["High Salary"]=df["Salary"]>60000

In [ ]:
df["Annual Salary"]=df["Salary"]*12

In [ ]:
df

  Employee Department  Salary    Bonus Country  High Salary  Annual Salary
0    Alice    Finance   80000  82500.0   India         True         900000
1      Bob         HR   70000  71500.0   India         True         780000
2  Charlie         IT   90000  93500.0   India         True        1020000
3    David      Sales   75000  77000.0   India         True         840000

## **Dropping & Renaming Columns**

In [9]:
df=df.drop(columns="Country")

KeyError: "['Country'] not found in axis"

In [10]:
df=df.drop(columns=["Bonus","High Salary"])

KeyError: "['Bonus', 'High Salary'] not found in axis"

In [11]:
df=df.rename(columns={"Employee":"Name"})

In [12]:
df

      Name Department  Salary
0    Alice    Finance   60000
1     John    Finance   50000
2      Bob         HR   50000
3  Charlie         IT   70000
4    David    Finance   70000
5     Emma         HR   65000

## **Missing Values**

In [27]:
# Sample dataset for missing values

import numpy as np
employee1 = {
    "Employee": ["Alice", "Bob", "Charlie", "David"],
    "Department": ["Finance", "HR", "IT", np.nan],
    "Salary": [60000, np.nan, 70000, 55000]
}

df3 = pd.DataFrame(employee1)

In [15]:
df3.isna()

   Employee  Department  Salary
0     False       False   False
1     False       False    True
2     False       False   False
3     False        True   False

In [ ]:
df3.isna().sum()

Employee      0
Department    1
Salary        1
dtype: int64

In [ ]:
df3.isna().sum().idxmax()  # to return column name of highest no of missing values

'Department'

## **Handling Missing Values**

In [ ]:
df3.dropna() # drop the rows with NaN

  Employee Department   Salary
0    Alice    Finance  60000.0
2  Charlie         IT  70000.0

In [ ]:
df3.fillna("Unknown")

  Employee Department   Salary
0    Alice    Finance  60000.0
1      Bob         HR  Unknown
2  Charlie         IT  70000.0
3    David    Unknown  55000.0

In [28]:
df3["Salary"] = df3["Salary"].fillna(0)
df3

  Employee Department   Salary
0    Alice    Finance  60000.0
1      Bob         HR      0.0
2  Charlie         IT  70000.0
3    David        NaN  55000.0

In [29]:
employee2 = {
    "Employee": ["Alice", "Bob", "Charlie", "David"],
    "Department": ["Finance", "HR", "IT", np.nan],
    "Salary": [60000, np.nan, 70000, 55000]
}

df3 = pd.DataFrame(employee2)
df3["Salary"] = df3["Salary"].fillna(round(df3["Salary"].mean()
))

In [30]:
df3

  Employee Department   Salary
0    Alice    Finance  60000.0
1      Bob         HR  61667.0
2  Charlie         IT  70000.0
3    David        NaN  55000.0

## **GroupBy**

In [ ]:
import pandas as pd

employee_data = {
    "Employee": ["Alice", "John", "Bob", "Charlie", "David", "Emma", "Kevin", "Sophia"],
    "Department": ["Finance", "Finance", "HR", "IT", "Finance", "HR", "IT", "Finance"],
    "Gender": ["Female", "Male", "Male", "Male", "Male", "Female", "Male", "Female"],
    "Salary": [60000, 50000, 50000, 70000, 70000, 65000, 75000, 80000]
}

emp_df = pd.DataFrame(employee_data)

In [ ]:
emp_df.groupby("Department")["Salary"].mean()

Department
Finance    65000.0
HR         57500.0
IT         72500.0
Name: Salary, dtype: float64

In [ ]:
emp_df.groupby("Department")["Salary"].sum()

Department
Finance    260000
HR         115000
IT         145000
Name: Salary, dtype: int64

In [ ]:
emp_df.groupby("Department")["Employee"].count()

Department
Finance    4
HR         2
IT         2
Name: Employee, dtype: int64

In [ ]:
emp_df.groupby("Department")["Salary"].agg(["mean","sum","min","max","count"])

               mean     sum    min    max  count
Department
Finance     65000.0  260000  50000  80000      4
HR          57500.0  115000  50000  65000      2
IT          72500.0  145000  70000  75000      2

In [ ]:
emp_df.groupby(["Department","Gender"])["Salary"].agg("mean")

Department  Gender
Finance     Female    70000.0
            Male      60000.0
HR          Female    65000.0
            Male      50000.0
IT          Male      72500.0
Name: Salary, dtype: float64

## **Merging DataFrames (merge())**

In [67]:
employees={
    "EmployeeID":[101,102,103,104],
    "Name":["Alice","Bob","charlie","David"],
    "DepartmentID":[1,2,1,3]
    }
empl_df=pd.DataFrame(employees)

In [68]:
departments = {
    "DepartmentID": [1,2,3],
    "Department": ["Finance","HR","IT"]
}

dep_df = pd.DataFrame(departments)

In [69]:
pd.merge(empl_df,dep_df,on="DepartmentID")

   EmployeeID     Name  DepartmentID Department
0         101    Alice             1    Finance
1         102      Bob             2         HR
2         103  charlie             1    Finance
3         104    David             3         IT

In [70]:
pd.merge(empl_df,dep_df,on="DepartmentID",how="left")

   EmployeeID     Name  DepartmentID Department
0         101    Alice             1    Finance
1         102      Bob             2         HR
2         103  charlie             1    Finance
3         104    David             3         IT

In [71]:
pd.merge(empl_df,dep_df,on="DepartmentID",how="outer")

   EmployeeID     Name  DepartmentID Department
0         101    Alice             1    Finance
1         103  charlie             1    Finance
2         102      Bob             2         HR
3         104    David             3         IT

## **Pivot Tables**

In [65]:
sales_data = {
    "Region": ["North","North","North","South","South","South","East","East","West","West"],
    "Category": ["Electronics","Furniture","Electronics","Furniture","Electronics","Furniture","Electronics","Furniture","Electronics","Furniture"],
    "Salesperson": ["Alice","Bob","Alice","Charlie","David","Charlie","Emma","Emma","Frank","Frank"],
    "Gender": ["F","M","F","M","M","M","F","F","M","M"],
    "Sales": [5000,3000,7000,4000,6000,3500,8000,4500,9000,5000],
    "Profit": [1000,500,1800,700,1200,600,2000,900,2500,1000]
}

sales_df = pd.DataFrame(sales_data)

sales_df

  Region     Category Salesperson Gender  Sales  Profit
0  North  Electronics       Alice      F   5000    1000
1  North    Furniture         Bob      M   3000     500
2  North  Electronics       Alice      F   7000    1800
3  South    Furniture     Charlie      M   4000     700
4  South  Electronics       David      M   6000    1200
5  South    Furniture     Charlie      M   3500     600
6   East  Electronics        Emma      F   8000    2000
7   East    Furniture        Emma      F   4500     900
8   West  Electronics       Frank      M   9000    2500
9   West    Furniture       Frank      M   5000    1000

In [34]:
pd.pivot_table(sales_df,index="Region",values="Sales",aggfunc="mean")

         Sales
Region
East    6250.0
North   5000.0
South   4500.0
West    7000.0

In [37]:
pd.pivot_table(sales_df,index="Category",values="Profit",aggfunc="sum")

             Profit
Category
Electronics    8500
Furniture      3700

In [59]:
pd.pivot_table(sales_df,
               index="Region"
               ,columns="Category"
               ,values="Sales"
               ,aggfunc="sum",
               sort = False  # to make table not to sort
)

Category  Electronics  Furniture
Region
North           12000       3000
South            6000       7500
East             8000       4500
West             9000       5000

In [46]:
pd.pivot_table(sales_df,
               index=["Region","Category"],
               columns="Gender",
               values="Sales",
               aggfunc="mean",
               dropna=False,) # used when an entire NaN column is needed(actually deletes automatically if so)

Gender                   F       M
Region Category
East   Electronics  8000.0     NaN
       Furniture    4500.0     NaN
North  Electronics  6000.0     NaN
       Furniture       NaN  3000.0
South  Electronics     NaN  6000.0
       Furniture       NaN  3750.0
West   Electronics     NaN  9000.0
       Furniture       NaN  5000.0

In [51]:
pivot=pd.pivot_table(sales_df,index="Region",values=["Sales","Profit"],aggfunc="mean")

pivot.rename(columns={"Profit":"Avg Profit","Sales":"Avg Sales"})

         Avg Profit  Avg Sales
Region
East    1450.000000     6250.0
North   1100.000000     5000.0
South    833.333333     4500.0
West    1750.000000     7000.0

In [66]:
pd.pivot_table(sales_df,
               index="Region",
               values="Sales",
               aggfunc=["mean","sum","count","max"],
               margins=True, margins_name="Grand Total") #grand total[for mean it gives overall avg]

               mean    sum count   max
              Sales  Sales Sales Sales
Region
East         6250.0  12500     2  8000
North        5000.0  15000     3  7000
South        4500.0  13500     3  6000
West         7000.0  14000     2  9000
Grand Total  5500.0  55000    10  9000

In [63]:
pivot1=pd.pivot_table(sales_df,
               index=["Region","Category"],
               columns="Gender",values=["Sales","Profit"],
               aggfunc=["mean","sum"],
               fill_value=0,  #filling Nan with 0
               )
pivot1.columns=["_".join(map(str,col))    # used for Flattening MultiIndex columns(rename)
                for col in pivot1.columns
]
display(pivot1)

                    mean_Profit_F  mean_Profit_M  mean_Sales_F  mean_Sales_M  \
Region Category
East   Electronics         2000.0            0.0        8000.0           0.0
       Furniture            900.0            0.0        4500.0           0.0
North  Electronics         1400.0            0.0        6000.0           0.0
       Furniture              0.0          500.0           0.0        3000.0
South  Electronics            0.0         1200.0           0.0        6000.0
       Furniture              0.0          650.0           0.0        3750.0
West   Electronics            0.0         2500.0           0.0        9000.0
       Furniture              0.0         1000.0           0.0        5000.0

                    sum_Profit_F  sum_Profit_M  sum_Sales_F  sum_Sales_M
Region Category
East   Electronics          2000             0         8000            0
       Furniture             900             0         4500            0
North  Electronics          2800             0        12000            0
       Furniture               0           500            0         3000
South  Electronics             0          1200            0         6000
       Furniture               0          1300            0         7500
West   Electronics             0          2500            0         9000
       Furniture               0          1000            0         5000

In [64]:
# Different aggregation for each value column
pd.pivot_table(
    sales_df,
    index="Region",
    values=["Sales", "Profit"],
    aggfunc={
        "Sales": "mean",
        "Profit": "sum"
    }
)

        Profit   Sales
Region
East      2900  6250.0
North     3300  5000.0
South     2500  4500.0
West      3500  7000.0

## **String Operations (.str)**

### **Dataset**

In [140]:
import pandas as pd

employee_data = {
    "Employee": [
        " alice ",
        "BOB",
        "charLie",
        " DAVID ",
        " emma ",
        "John Doe",
        "SARA ALI",
        "  kevin joseph  ",
        "michael smith",
        " ANNA "
    ],

    "Department": [
        "finance",
        " HR ",
        "it",
        "Finance",
        " hr ",
        "IT",
        "FINANCE",
        "sales ",
        " Marketing",
        "finance "
    ],

    "Email": [
        "alice@gmail.com",
        "BOB@GMAIL.COM",
        "charlie@yahoo.com",
        " david@hotmail.com ",
        "emma@gmail.com",
        "john.doe@gmail.com",
        "SARA@YAHOO.COM",
        " kevin@gmail.com ",
        "michael@outlook.com",
        " ANNA@GMAIL.COM "
    ],

    "Employee ID":[
        "EMP101",
        "EMP102",
        "EMP103",
        "EMP104",
        "EMP105",
        "EMP106",
        "EMP107",
        "EMP108",
        "EMP109",
        "EMP110"
    ]
}

e_df = pd.DataFrame(employee_data)

e_df

           Employee  Department                Email Employee ID
0            alice      finance      alice@gmail.com      EMP101
1               BOB         HR         BOB@GMAIL.COM      EMP102
2           charLie          it    charlie@yahoo.com      EMP103
3            DAVID      Finance   david@hotmail.com       EMP104
4             emma          hr        emma@gmail.com      EMP105
5          John Doe          IT   john.doe@gmail.com      EMP106
6          SARA ALI     FINANCE       SARA@YAHOO.COM      EMP107
7    kevin joseph        sales      kevin@gmail.com       EMP108
8     michael smith   Marketing  michael@outlook.com      EMP109
9             ANNA     finance       ANNA@GMAIL.COM       EMP110

### **Questions(18)**

In [74]:
e_df["Employee"].str.upper() #uppercase

0              ALICE
1                 BOB
2             CHARLIE
3              DAVID
4               EMMA
5            JOHN DOE
6            SARA ALI
7      KEVIN JOSEPH
8       MICHAEL SMITH
9               ANNA
Name: Employee, dtype: object

In [75]:
e_df["Employee"].str.lower() #lowercase

0              alice
1                 bob
2             charlie
3              david
4               emma
5            john doe
6            sara ali
7      kevin joseph
8       michael smith
9               anna
Name: Employee, dtype: object

In [79]:
e_df["Employee"].str.title() #first letter of words caps

0              Alice
1                 Bob
2             Charlie
3              David
4               Emma
5            John Doe
6            Sara Ali
7      Kevin Joseph
8       Michael Smith
9               Anna
Name: Employee, dtype: object

In [150]:
e_df["Employee"].str.strip().str.capitalize() #to caps 1st letter

0            Alice
1              Bob
2          Charlie
3            David
4             Emma
5         John doe
6         Sara ali
7     Kevin joseph
8    Michael smith
9             Anna
Name: Employee, dtype: object

In [152]:
e_df[["Employee","Email","Department"]]=(
    e_df[["Employee","Email","Department"]]
    .apply(lambda col: col.str.strip())  #strip for multiple columns
    )
display(e_df)

        Employee Department                Email Employee ID  Length
0          alice    finance      alice@gmail.com      EMP101       7
1            BOB         HR        BOB@GMAIL.COM      EMP102       3
2        charLie         it    charlie@yahoo.com      EMP103       7
3          DAVID    Finance    david@hotmail.com      EMP104       7
4           emma         hr       emma@gmail.com      EMP105       6
5       John Doe         IT   john.doe@gmail.com      EMP106       8
6       SARA ALI    FINANCE       SARA@YAHOO.COM      EMP107       8
7   kevin joseph      sales      kevin@gmail.com      EMP108      16
8  michael smith  Marketing  michael@outlook.com      EMP109      13
9           ANNA    finance       ANNA@GMAIL.COM      EMP110       6

In [97]:
e_df["Employee"].str.contains("a",case=False) #contains- ignoring case

0     True
1    False
2     True
3     True
4     True
5    False
6     True
7    False
8     True
9     True
Name: Employee, dtype: bool

In [106]:
e_df["Email"].str.lower().str.contains("gmail",case=False) #contains - ignoring case

0     True
1     True
2    False
3    False
4     True
5     True
6    False
7     True
8    False
9     True
Name: Email, dtype: bool

In [100]:
e_df["Employee"].str.lower().str.startswith("a") #startswith - use lower or upper(to ignore case)

0     True
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9     True
Name: Employee, dtype: bool

In [104]:
e_df["Email"].str.lower().str.endswith(".com") #endswith [same as startswith]

0    True
1    True
2    True
3    True
4    True
5    True
6    True
7    True
8    True
9    True
Name: Email, dtype: bool

In [136]:
e_df["Department"]=e_df["Department"].str.strip().str.upper().str.replace("FINANCE","ACCOUNTS")
e_df # to replace values - use upper/lower before that

,Employee,Department,Email,Employee ID,Length,First Name,Last Name,Employee Info
0,alice,ACCOUNTS,alice@gmail.com,EMP101,5,alice,,alice - finance
1,BOB,HR,BOB@GMAIL.COM,EMP102,3,BOB,,BOB - HR
2,charLie,IT,charlie@yahoo.com,EMP103,7,charLie,,charLie - it
3,DAVID,ACCOUNTS,david@hotmail.com,EMP104,5,DAVID,,DAVID - Finance
4,emma,HR,emma@gmail.com,EMP105,4,emma,,emma - hr
5,John Doe,IT,john.doe@gmail.com,EMP106,8,John,Doe,John Doe - IT
6,SARA ALI,ACCOUNTS,SARA@YAHOO.COM,EMP107,8,SARA,ALI,SARA ALI - FINANCE
7,kevin joseph,SALES,kevin@gmail.com,EMP108,12,kevin,joseph,kevin joseph - sales
8,michael smith,MARKETING,michael@outlook.com,EMP109,13,michael,smith,michael smith - Marketing
9,ANNA,ACCOUNTS,ANNA@GMAIL.COM,EMP110,4,ANNA,,ANNA - finance

In [107]:
e_df["Employee"].str.len() # length

0     5
1     3
2     7
3     5
4     4
5     8
6     8
7    12
8    13
9     4
Name: Employee, dtype: int64

In [143]:
e_df["Length"]=e_df["Employee"].str.len() #create temp column with length
e_df.loc[e_df["Length"].idxmax()] #use np fn to get the row of max(use "name" to get only max name)

Employee          kevin joseph
Department                sales
Email           kevin@gmail.com
Employee ID               EMP108
Length                        16
Name: 7, dtype: object

In [111]:
e_df["Employee"].str.split(" ") #to split it as list

0             [alice]
1               [BOB]
2           [charLie]
3             [DAVID]
4              [emma]
5         [John, Doe]
6         [SARA, ALI]
7     [kevin, joseph]
8    [michael, smith]
9              [ANNA]
Name: Employee, dtype: object

In [115]:
e_df[['First Name','Last Name']]=e_df["Employee"].str.split(" ",expand=True) # to split 1st, last name(expand)
e_df["Last Name"]=e_df["Last Name"].fillna("") # to fill Nan with ""
e_df

,Employee,Department,Email,Employee ID,Length,First Name,Last Name
0,alice,finance,alice@gmail.com,EMP101,5,alice,
1,BOB,HR,BOB@GMAIL.COM,EMP102,3,BOB,
2,charLie,it,charlie@yahoo.com,EMP103,7,charLie,
3,DAVID,Finance,david@hotmail.com,EMP104,5,DAVID,
4,emma,hr,emma@gmail.com,EMP105,4,emma,
5,John Doe,IT,john.doe@gmail.com,EMP106,8,John,Doe
6,SARA ALI,FINANCE,SARA@YAHOO.COM,EMP107,8,SARA,ALI
7,kevin joseph,sales,kevin@gmail.com,EMP108,12,kevin,joseph
8,michael smith,Marketing,michael@outlook.com,EMP109,13,michael,smith
9,ANNA,finance,ANNA@GMAIL.COM,EMP110,4,ANNA,

In [120]:
display(e_df["Employee"].str[:3], #slicing
        e_df["Employee"].str.slice(0,3) #slicing with slice fn
        )

0    ali
1    BOB
2    cha
3    DAV
4    emm
5    Joh
6    SAR
7    kev
8    mic
9    ANN
Name: Employee, dtype: object

0    ali
1    BOB
2    cha
3    DAV
4    emm
5    Joh
6    SAR
7    kev
8    mic
9    ANN
Name: Employee, dtype: object

In [127]:
e_df["Employee"].str.lower().str.count("a") #to count (use same case-upper/lower)

0    1
1    0
2    1
3    1
4    1
5    0
6    3
7    0
8    1
9    2
Name: Employee, dtype: int64

In [153]:
e_df["Employee ID"].str.extract(r'(\d+)') #extract to get particular part of col as newcol

     0
0  101
1  102
2  103
3  104
4  105
5  106
6  107
7  108
8  109
9  110

In [134]:
e_df["Employee Info"]=e_df["Employee"].str.cat(e_df["Department"],sep=" - ") #concat
e_df

,Employee,Department,Email,Employee ID,Length,First Name,Last Name,Employee Info
0,alice,finance,alice@gmail.com,EMP101,5,alice,,alice - finance
1,BOB,HR,BOB@GMAIL.COM,EMP102,3,BOB,,BOB - HR
2,charLie,it,charlie@yahoo.com,EMP103,7,charLie,,charLie - it
3,DAVID,Finance,david@hotmail.com,EMP104,5,DAVID,,DAVID - Finance
4,emma,hr,emma@gmail.com,EMP105,4,emma,,emma - hr
5,John Doe,IT,john.doe@gmail.com,EMP106,8,John,Doe,John Doe - IT
6,SARA ALI,FINANCE,SARA@YAHOO.COM,EMP107,8,SARA,ALI,SARA ALI - FINANCE
7,kevin joseph,sales,kevin@gmail.com,EMP108,12,kevin,joseph,kevin joseph - sales
8,michael smith,Marketing,michael@outlook.com,EMP109,13,michael,smith,michael smith - Marketing
9,ANNA,finance,ANNA@GMAIL.COM,EMP110,4,ANNA,,ANNA - finance

In [148]:
display(e_df["Employee"].str.split().str.get(0),e_df["Employee"].str.split().str.get(1)) #geting the element after splitting

0      alice
1        BOB
2    charLie
3      DAVID
4       emma
5       John
6       SARA
7      kevin
8    michael
9       ANNA
Name: Employee, dtype: object

0       NaN
1       NaN
2       NaN
3       NaN
4       NaN
5       Doe
6       ALI
7    joseph
8     smith
9       NaN
Name: Employee, dtype: object

## **Date & Time Handling**