# **Pandas Reference Notebook**

### Contents

1. Creating DataFrames
2. Inspecting Data
3. Selecting Columns
4. Selecting Rows
5. Filtering Rows
6. Sorting Data
7. Adding & Modifying Columns
8. Dropping & Renaming Columns
9. Missing Values
10. Handling Missing Values
11. GroupBy
12. Merging DataFrames
13. Concatenating DataFrames
14. Pivot Tables
15. Reshaping Data (`melt`)
16. Cross Tabulation (`crosstab`)
17. String Operations
18. Date & Time Handling
19. `map()`, `apply()`, and `lambda`
20. Reading Data Sources
21. Data Analysis Workflow

In [217]:
import pandas as pd
import numpy as np

## **Creating Dataframe**

In [218]:
employee={"Employee":["Alice","Bob","Charlie","David"], "Department":["Finance","HR","IT","Sales"],"Salary":[60000,50000,70000,55000]}
df=pd.DataFrame(employee)
df

  Employee Department  Salary
0    Alice    Finance   60000
1      Bob         HR   50000
2  Charlie         IT   70000
3    David      Sales   55000

## **Inspecting Data**

In [219]:
display(df.head())
display(df.head(2))

  Employee Department  Salary
0    Alice    Finance   60000
1      Bob         HR   50000
2  Charlie         IT   70000
3    David      Sales   55000

  Employee Department  Salary
0    Alice    Finance   60000
1      Bob         HR   50000

In [220]:
display(df.tail())
display(df.tail(2))

  Employee Department  Salary
0    Alice    Finance   60000
1      Bob         HR   50000
2  Charlie         IT   70000
3    David      Sales   55000

  Employee Department  Salary
2  Charlie         IT   70000
3    David      Sales   55000

In [221]:
df.shape

(4, 3)

In [222]:
df.columns

Index(['Employee', 'Department', 'Salary'], dtype='object')

In [223]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Employee    4 non-null      object
 1   Department  4 non-null      object
 2   Salary      4 non-null      int64
dtypes: int64(1), object(2)
memory usage: 228.0+ bytes

In [224]:
display(df.describe()) #numerical summary
print("\n")
display(df.describe(include="all")) #summary all of all cols
print("\n")
display(df.describe(include="object")) #categorical/text summary

             Salary
count      4.000000
mean   58750.000000
std     8539.125638
min    50000.000000
25%    53750.000000
50%    57500.000000
75%    62500.000000
max    70000.000000

       Employee Department        Salary
count         4          4      4.000000
unique        4          4           NaN
top       Alice    Finance           NaN
freq          1          1           NaN
mean        NaN        NaN  58750.000000
std         NaN        NaN   8539.125638
min         NaN        NaN  50000.000000
25%         NaN        NaN  53750.000000
50%         NaN        NaN  57500.000000
75%         NaN        NaN  62500.000000
max         NaN        NaN  70000.000000

       Employee Department
count         4          4
unique        4          4
top       Alice    Finance
freq          1          1

In [225]:
display(df.memory_usage()) #to check memory
display(df.memory_usage().sum()) #total memory
display(df.memory_usage(deep=True).sum()) #total memory inc. object/str data [for mb use "/(1024**2)"]

Index         132
Employee       32
Department     32
Salary         32
dtype: int64

np.int64(228)

np.int64(592)

In [226]:
pd.set_option("display.max_columns",None) # to disable truncation of cols

In [227]:
df.sample(3) #random 3 rows

  Employee Department  Salary
2  Charlie         IT   70000
0    Alice    Finance   60000
3    David      Sales   55000

In [228]:
df.nunique() #unique values

Employee      4
Department    4
Salary        4
dtype: int64

## **Selecting Columns**

In [229]:
display(df["Salary"])
display(df["Department"])
display(df[["Employee","Salary"]])
display(df[["Department","Salary"]])

0    60000
1    50000
2    70000
3    55000
Name: Salary, dtype: int64

0    Finance
1         HR
2         IT
3      Sales
Name: Department, dtype: object

  Employee  Salary
0    Alice   60000
1      Bob   50000
2  Charlie   70000
3    David   55000

  Department  Salary
0    Finance   60000
1         HR   50000
2         IT   70000
3      Sales   55000

## **Selecting Rows**

In [230]:
# iloc(Integer Location) - # loc - use label-based indexing (row labels and column names)

display(df.iloc[0])
display(df.iloc[:2])
print(df.iloc[1,2])
display(df.iloc[:2,:2])

Employee        Alice
Department    Finance
Salary          60000
Name: 0, dtype: object

  Employee Department  Salary
0    Alice    Finance   60000
1      Bob         HR   50000

50000

  Employee Department
0    Alice    Finance
1      Bob         HR

In [231]:
# loc(Location) - use for row name & column name(can use if index number is changed)


display(df.loc[0])
display(df.loc[:2])
print("\n")
print(df.loc[1,"Salary"])     # need to type the column names
display(df.loc[:2,["Employee","Department"]])     # here 2 is included

Employee        Alice
Department    Finance
Salary          60000
Name: 0, dtype: object

  Employee Department  Salary
0    Alice    Finance   60000
1      Bob         HR   50000
2  Charlie         IT   70000

50000

  Employee Department
0    Alice    Finance
1      Bob         HR
2  Charlie         IT

## **Filtering Rows**

In [232]:
df[df["Salary"]>55000]

  Employee Department  Salary
0    Alice    Finance   60000
2  Charlie         IT   70000

In [233]:
df[df["Department"]=="Sales"]

  Employee Department  Salary
3    David      Sales   55000

In [234]:
df[(df["Salary"]<=55000)]

  Employee Department  Salary
1      Bob         HR   50000
3    David      Sales   55000

In [235]:
df[(df["Department"]=="Finance") | (df["Department"]=="IT")]

  Employee Department  Salary
0    Alice    Finance   60000
2  Charlie         IT   70000

In [236]:
df[(df["Department"]=="Finance") & (df["Salary"]>55000)]

  Employee Department  Salary
0    Alice    Finance   60000

## **Sorting Data (sort_values())**

In [237]:
df.sort_values("Salary")

  Employee Department  Salary
1      Bob         HR   50000
3    David      Sales   55000
0    Alice    Finance   60000
2  Charlie         IT   70000

In [238]:
df.sort_values("Salary",ascending=False)

  Employee Department  Salary
2  Charlie         IT   70000
0    Alice    Finance   60000
3    David      Sales   55000
1      Bob         HR   50000

In [239]:
df.sort_values("Department")

  Employee Department  Salary
0    Alice    Finance   60000
1      Bob         HR   50000
2  Charlie         IT   70000
3    David      Sales   55000

In [240]:
# Sample datset for multiple columns

employee = {
    "Employee": ["Alice","John","Bob","Charlie","David","Emma"],
    "Department": ["Finance","Finance","HR","IT","Finance","HR"],
    "Salary": [60000,50000,50000,70000,70000,65000]
}

df = pd.DataFrame(employee)

In [241]:
df.sort_values(["Department","Salary"])

  Employee Department  Salary
1     John    Finance   50000
0    Alice    Finance   60000
4    David    Finance   70000
2      Bob         HR   50000
5     Emma         HR   65000
3  Charlie         IT   70000

## **Adding & Modifying Columns**

In [242]:
df["Salary"]=df["Salary"]+5000

In [243]:
df["Bonus"]=df["Salary"]*1.10

In [244]:
df["Country"]="India"

In [245]:
df["High Salary"]=df["Salary"]>60000

In [246]:
df["Annual Salary"]=df["Salary"]*12

In [247]:
df

  Employee Department  Salary    Bonus Country  High Salary  Annual Salary
0    Alice    Finance   65000  71500.0   India         True         780000
1     John    Finance   55000  60500.0   India        False         660000
2      Bob         HR   55000  60500.0   India        False         660000
3  Charlie         IT   75000  82500.0   India         True         900000
4    David    Finance   75000  82500.0   India         True         900000
5     Emma         HR   70000  77000.0   India         True         840000

## **Dropping & Renaming Columns**

In [248]:
df=df.drop(columns="Country")

In [249]:
df=df.drop(columns=["Bonus","High Salary"])

In [250]:
df=df.rename(columns={"Employee":"Name"})

In [251]:
df

      Name Department  Salary  Annual Salary
0    Alice    Finance   65000         780000
1     John    Finance   55000         660000
2      Bob         HR   55000         660000
3  Charlie         IT   75000         900000
4    David    Finance   75000         900000
5     Emma         HR   70000         840000

## **Missing Values**

### **Dataset**

In [252]:
# Sample dataset for missing values

import numpy as np
employee1 = {
    "Employee": ["Alice", "Bob", "Charlie", "David"],
    "Department": ["Finance", "HR", "IT", np.nan],
    "Salary": [60000, np.nan, 70000, 55000]
}

df3 = pd.DataFrame(employee1)

### **Code**

In [253]:
df3.isna()

   Employee  Department  Salary
0     False       False   False
1     False       False    True
2     False       False   False
3     False        True   False

In [254]:
df3.isna().sum()

Employee      0
Department    1
Salary        1
dtype: int64

In [255]:
df3.isna().sum().idxmax()  # to return column name of highest no of missing values

'Department'

## **Handling Missing Values**

In [256]:
df3.dropna() # drop the rows with NaN

  Employee Department   Salary
0    Alice    Finance  60000.0
2  Charlie         IT  70000.0

In [257]:
df3.fillna("Unknown")

  Employee Department   Salary
0    Alice    Finance  60000.0
1      Bob         HR  Unknown
2  Charlie         IT  70000.0
3    David    Unknown  55000.0

In [258]:
df3["Salary"] = df3["Salary"].fillna(0)
df3

  Employee Department   Salary
0    Alice    Finance  60000.0
1      Bob         HR      0.0
2  Charlie         IT  70000.0
3    David        NaN  55000.0

In [259]:
employee2 = {
    "Employee": ["Alice", "Bob", "Charlie", "David"],
    "Department": ["Finance", "HR", "IT", np.nan],
    "Salary": [60000, np.nan, 70000, 55000]
}

df3 = pd.DataFrame(employee2)

df3["Salary"] = df3["Salary"].fillna(round(df3["Salary"].mean()))

In [260]:
df3

  Employee Department   Salary
0    Alice    Finance  60000.0
1      Bob         HR  61667.0
2  Charlie         IT  70000.0
3    David        NaN  55000.0

## **GroupBy**

### **Dataset**

In [261]:
import pandas as pd

employee_data = {
    "Employee": ["Alice", "John", "Bob", "Charlie", "David", "Emma", "Kevin", "Sophia"],
    "Department": ["Finance", "Finance", "HR", "IT", "Finance", "HR", "IT", "Finance"],
    "Gender": ["Female", "Male", "Male", "Male", "Male", "Female", "Male", "Female"],
    "Salary": [60000, 50000, 50000, 70000, 70000, 65000, 75000, 80000]
}

emp_df = pd.DataFrame(employee_data)

### **Code**

In [262]:
emp_df.groupby("Department")["Salary"].mean()

Department
Finance    65000.0
HR         57500.0
IT         72500.0
Name: Salary, dtype: float64

In [263]:
emp_df.groupby("Department")["Salary"].sum()

Department
Finance    260000
HR         115000
IT         145000
Name: Salary, dtype: int64

In [264]:
emp_df.groupby("Department")["Employee"].count()

Department
Finance    4
HR         2
IT         2
Name: Employee, dtype: int64

In [265]:
emp_df.groupby("Department")["Salary"].agg(["mean","sum","min","max","count"])

               mean     sum    min    max  count
Department
Finance     65000.0  260000  50000  80000      4
HR          57500.0  115000  50000  65000      2
IT          72500.0  145000  70000  75000      2

In [266]:
emp_df.groupby(["Department","Gender"])["Salary"].agg("mean")

Department  Gender
Finance     Female    70000.0
            Male      60000.0
HR          Female    65000.0
            Male      50000.0
IT          Male      72500.0
Name: Salary, dtype: float64

## **Merging DataFrames (merge())**

### **Datasets**

In [267]:
employees={
    "EmployeeID":[101,102,103,104],
    "Name":["Alice","Bob","charlie","David"],
    "DepartmentID":[1,2,1,3]
    }
empl_df=pd.DataFrame(employees)

In [268]:
departments = {
    "DepartmentID": [1,2,3],
    "Department": ["Finance","HR","IT"]
}

dep_df = pd.DataFrame(departments)

### **Code**

In [269]:
pd.merge(empl_df,dep_df,on="DepartmentID")

   EmployeeID     Name  DepartmentID Department
0         101    Alice             1    Finance
1         102      Bob             2         HR
2         103  charlie             1    Finance
3         104    David             3         IT

In [270]:
pd.merge(empl_df,dep_df,on="DepartmentID",how="left")

   EmployeeID     Name  DepartmentID Department
0         101    Alice             1    Finance
1         102      Bob             2         HR
2         103  charlie             1    Finance
3         104    David             3         IT

In [271]:
pd.merge(empl_df,dep_df,on="DepartmentID",how="outer")

   EmployeeID     Name  DepartmentID Department
0         101    Alice             1    Finance
1         103  charlie             1    Finance
2         102      Bob             2         HR
3         104    David             3         IT

## **Concatenating DataFrames (concat())**

### **Datasets**

In [272]:
jan_sales = pd.DataFrame({ "Month":["Jan","Jan"], "Sales":[1000,2000] })

In [273]:
feb_sales = pd.DataFrame({ "Month":["Feb","Feb"], "Sales":[1500,2500] })

### **Code**

In [274]:
pd.concat([jan_sales,feb_sales],ignore_index=True)

  Month  Sales
0   Jan   1000
1   Jan   2000
2   Feb   1500
3   Feb   2500

In [275]:
pd.concat([jan_sales,feb_sales],axis=1) #horizontal concat

  Month  Sales Month  Sales
0   Jan   1000   Feb   1500
1   Jan   2000   Feb   2500

## **Pivot Tables**

### **Dataset**

In [276]:
sales_data = {
    "Region": ["North","North","North","South","South","South","East","East","West","West"],
    "Category": ["Electronics","Furniture","Electronics","Furniture","Electronics","Furniture","Electronics","Furniture","Electronics","Furniture"],
    "Salesperson": ["Alice","Bob","Alice","Charlie","David","Charlie","Emma","Emma","Frank","Frank"],
    "Gender": ["F","M","F","M","M","M","F","F","M","M"],
    "Sales": [5000,3000,7000,4000,6000,3500,8000,4500,9000,5000],
    "Profit": [1000,500,1800,700,1200,600,2000,900,2500,1000]
}

sales_df = pd.DataFrame(sales_data)

sales_df

  Region     Category Salesperson Gender  Sales  Profit
0  North  Electronics       Alice      F   5000    1000
1  North    Furniture         Bob      M   3000     500
2  North  Electronics       Alice      F   7000    1800
3  South    Furniture     Charlie      M   4000     700
4  South  Electronics       David      M   6000    1200
5  South    Furniture     Charlie      M   3500     600
6   East  Electronics        Emma      F   8000    2000
7   East    Furniture        Emma      F   4500     900
8   West  Electronics       Frank      M   9000    2500
9   West    Furniture       Frank      M   5000    1000

### **Code**

In [277]:
pd.pivot_table(sales_df,index="Region",values="Sales",aggfunc="mean")

         Sales
Region
East    6250.0
North   5000.0
South   4500.0
West    7000.0

In [278]:
pd.pivot_table(sales_df,index="Category",values="Profit",aggfunc="sum")

             Profit
Category
Electronics    8500
Furniture      3700

In [279]:
pd.pivot_table(sales_df,
               index="Region"
               ,columns="Category"
               ,values="Sales"
               ,aggfunc="sum",
               sort = False  # to make table not to sort
)

Category  Electronics  Furniture
Region
North           12000       3000
South            6000       7500
East             8000       4500
West             9000       5000

In [280]:
pd.pivot_table(sales_df,
               index=["Region","Category"],
               columns="Gender",
               values="Sales",
               aggfunc="mean",
               dropna=False,) # used when an entire NaN column is needed(actually deletes automatically if so)

Gender                   F       M
Region Category
East   Electronics  8000.0     NaN
       Furniture    4500.0     NaN
North  Electronics  6000.0     NaN
       Furniture       NaN  3000.0
South  Electronics     NaN  6000.0
       Furniture       NaN  3750.0
West   Electronics     NaN  9000.0
       Furniture       NaN  5000.0

In [281]:
pivot=pd.pivot_table(sales_df,index="Region",values=["Sales","Profit"],aggfunc="mean")

pivot.rename(columns={"Profit":"Avg Profit","Sales":"Avg Sales"})

         Avg Profit  Avg Sales
Region
East    1450.000000     6250.0
North   1100.000000     5000.0
South    833.333333     4500.0
West    1750.000000     7000.0

In [282]:
pd.pivot_table(sales_df,
               index="Region",
               values="Sales",
               aggfunc=["mean","sum","count","max"],
               margins=True, margins_name="Grand Total") #grand total[for mean it gives overall avg]

               mean    sum count   max
              Sales  Sales Sales Sales
Region
East         6250.0  12500     2  8000
North        5000.0  15000     3  7000
South        4500.0  13500     3  6000
West         7000.0  14000     2  9000
Grand Total  5500.0  55000    10  9000

In [283]:
pivot1=pd.pivot_table(sales_df,
               index=["Region","Category"],
               columns="Gender",values=["Sales","Profit"],
               aggfunc=["mean","sum"],
               fill_value=0,  #filling Nan with 0
               )
pivot1.columns=["_".join(map(str,col))    # used for Flattening MultiIndex columns(rename)
                for col in pivot1.columns
]
display(pivot1)

                    mean_Profit_F  mean_Profit_M  mean_Sales_F  mean_Sales_M  \
Region Category
East   Electronics         2000.0            0.0        8000.0           0.0
       Furniture            900.0            0.0        4500.0           0.0
North  Electronics         1400.0            0.0        6000.0           0.0
       Furniture              0.0          500.0           0.0        3000.0
South  Electronics            0.0         1200.0           0.0        6000.0
       Furniture              0.0          650.0           0.0        3750.0
West   Electronics            0.0         2500.0           0.0        9000.0
       Furniture              0.0         1000.0           0.0        5000.0

                    sum_Profit_F  sum_Profit_M  sum_Sales_F  sum_Sales_M
Region Category
East   Electronics          2000             0         8000            0
       Furniture             900             0         4500            0
North  Electronics          2800             0        12000            0
       Furniture               0           500            0         3000
South  Electronics             0          1200            0         6000
       Furniture               0          1300            0         7500
West   Electronics             0          2500            0         9000
       Furniture               0          1000            0         5000

In [284]:
# Different aggregation for each value column
pd.pivot_table(
    sales_df,
    index="Region",
    values=["Sales", "Profit"],
    aggfunc={
        "Sales": "mean",
        "Profit": "sum"
    }
)

        Profit   Sales
Region
East      2900  6250.0
North     3300  5000.0
South     2500  4500.0
West      3500  7000.0

## **Reshaping Data (melt()) & Cross Tabulation (crosstab())**

### **Dataset**

In [285]:
wide_df = pd.DataFrame({ "Region":["East","West"], "Tech":[1000,1200], "Furniture":[500,700] })

### **Code**

In [286]:
pd.melt(wide_df,id_vars="Region",
        var_name="Categories",
        value_name="Sales") #melt())

  Region Categories  Sales
0   East       Tech   1000
1   West       Tech   1200
2   East  Furniture    500
3   West  Furniture    700

In [287]:
pd.crosstab(sales_df["Region"],sales_df["Category"])

Category  Electronics  Furniture
Region
East                1          1
North               2          1
South               1          2
West                1          1

## **String Operations (.str)**

### **Dataset**

In [288]:
import pandas as pd

employee_data = {
    "Employee": [
        " alice ",
        "BOB",
        "charLie",
        " DAVID ",
        " emma ",
        "John Doe",
        "SARA ALI",
        "  kevin joseph  ",
        "michael smith",
        " ANNA "
    ],

    "Department": [
        "finance",
        " HR ",
        "it",
        "Finance",
        " hr ",
        "IT",
        "FINANCE",
        "sales ",
        " Marketing",
        "finance "
    ],

    "Email": [
        "alice@gmail.com",
        "BOB@GMAIL.COM",
        "charlie@yahoo.com",
        " david@hotmail.com ",
        "emma@gmail.com",
        "john.doe@gmail.com",
        "SARA@YAHOO.COM",
        " kevin@gmail.com ",
        "michael@outlook.com",
        " ANNA@GMAIL.COM "
    ],

    "Employee ID":[
        "EMP101",
        "EMP102",
        "EMP103",
        "EMP104",
        "EMP105",
        "EMP106",
        "EMP107",
        "EMP108",
        "EMP109",
        "EMP110"
    ]
}

e_df = pd.DataFrame(employee_data)

e_df

           Employee  Department                Email Employee ID
0            alice      finance      alice@gmail.com      EMP101
1               BOB         HR         BOB@GMAIL.COM      EMP102
2           charLie          it    charlie@yahoo.com      EMP103
3            DAVID      Finance   david@hotmail.com       EMP104
4             emma          hr        emma@gmail.com      EMP105
5          John Doe          IT   john.doe@gmail.com      EMP106
6          SARA ALI     FINANCE       SARA@YAHOO.COM      EMP107
7    kevin joseph        sales      kevin@gmail.com       EMP108
8     michael smith   Marketing  michael@outlook.com      EMP109
9             ANNA     finance       ANNA@GMAIL.COM       EMP110

### **Code**

In [289]:
e_df["Employee"].str.upper() #uppercase

0              ALICE
1                 BOB
2             CHARLIE
3              DAVID
4               EMMA
5            JOHN DOE
6            SARA ALI
7      KEVIN JOSEPH
8       MICHAEL SMITH
9               ANNA
Name: Employee, dtype: object

In [290]:
e_df["Employee"].str.lower() #lowercase

0              alice
1                 bob
2             charlie
3              david
4               emma
5            john doe
6            sara ali
7      kevin joseph
8       michael smith
9               anna
Name: Employee, dtype: object

In [291]:
e_df["Employee"].str.title() #first letter of words caps

0              Alice
1                 Bob
2             Charlie
3              David
4               Emma
5            John Doe
6            Sara Ali
7      Kevin Joseph
8       Michael Smith
9               Anna
Name: Employee, dtype: object

In [292]:
e_df["Employee"].str.strip().str.capitalize() #to caps 1st letter

0            Alice
1              Bob
2          Charlie
3            David
4             Emma
5         John doe
6         Sara ali
7     Kevin joseph
8    Michael smith
9             Anna
Name: Employee, dtype: object

In [293]:
e_df[["Employee","Email","Department"]]=(
    e_df[["Employee","Email","Department"]]
    .apply(lambda col: col.str.strip())  #strip for multiple columns
    )
display(e_df)

        Employee Department                Email Employee ID
0          alice    finance      alice@gmail.com      EMP101
1            BOB         HR        BOB@GMAIL.COM      EMP102
2        charLie         it    charlie@yahoo.com      EMP103
3          DAVID    Finance    david@hotmail.com      EMP104
4           emma         hr       emma@gmail.com      EMP105
5       John Doe         IT   john.doe@gmail.com      EMP106
6       SARA ALI    FINANCE       SARA@YAHOO.COM      EMP107
7   kevin joseph      sales      kevin@gmail.com      EMP108
8  michael smith  Marketing  michael@outlook.com      EMP109
9           ANNA    finance       ANNA@GMAIL.COM      EMP110

In [294]:
e_df["Employee"].str.contains("a",case=False) #contains- ignoring case

0     True
1    False
2     True
3     True
4     True
5    False
6     True
7    False
8     True
9     True
Name: Employee, dtype: bool

In [295]:
e_df["Email"].str.lower().str.contains("gmail",case=False) #contains - ignoring case

0     True
1     True
2    False
3    False
4     True
5     True
6    False
7     True
8    False
9     True
Name: Email, dtype: bool

In [296]:
e_df["Employee"].str.lower().str.startswith("a") #startswith - use lower or upper(to ignore case)

0     True
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9     True
Name: Employee, dtype: bool

In [297]:
e_df["Email"].str.lower().str.endswith(".com") #endswith [same as startswith]

0    True
1    True
2    True
3    True
4    True
5    True
6    True
7    True
8    True
9    True
Name: Email, dtype: bool

In [298]:
e_df["Department"]=e_df["Department"].str.strip().str.upper().str.replace("FINANCE","ACCOUNTS")
e_df # to replace values - use upper/lower before that

        Employee Department                Email Employee ID
0          alice   ACCOUNTS      alice@gmail.com      EMP101
1            BOB         HR        BOB@GMAIL.COM      EMP102
2        charLie         IT    charlie@yahoo.com      EMP103
3          DAVID   ACCOUNTS    david@hotmail.com      EMP104
4           emma         HR       emma@gmail.com      EMP105
5       John Doe         IT   john.doe@gmail.com      EMP106
6       SARA ALI   ACCOUNTS       SARA@YAHOO.COM      EMP107
7   kevin joseph      SALES      kevin@gmail.com      EMP108
8  michael smith  MARKETING  michael@outlook.com      EMP109
9           ANNA   ACCOUNTS       ANNA@GMAIL.COM      EMP110

In [299]:
e_df["Employee"].str.len() # length

0     5
1     3
2     7
3     5
4     4
5     8
6     8
7    12
8    13
9     4
Name: Employee, dtype: int64

In [300]:
e_df["Length"]=e_df["Employee"].str.len() #create temp column with length
e_df.loc[e_df["Length"].idxmax()] #use np fn(idxmax) to get the row of max-(use "name" to get only max name)

Employee             michael smith
Department               MARKETING
Email          michael@outlook.com
Employee ID                 EMP109
Length                          13
Name: 8, dtype: object

In [301]:
e_df["Employee"].str.split(" ") #to split it as list

0             [alice]
1               [BOB]
2           [charLie]
3             [DAVID]
4              [emma]
5         [John, Doe]
6         [SARA, ALI]
7     [kevin, joseph]
8    [michael, smith]
9              [ANNA]
Name: Employee, dtype: object

In [302]:
e_df[['First Name','Last Name']]=e_df["Employee"].str.split(" ",expand=True) # to split first, last name (expand for columns)
e_df["Last Name"]=e_df["Last Name"].fillna("") # to fill Nan with "" (blank)
e_df

,Employee,Department,Email,Employee ID,Length,First Name,Last Name
0,alice,ACCOUNTS,alice@gmail.com,EMP101,5,alice,
1,BOB,HR,BOB@GMAIL.COM,EMP102,3,BOB,
2,charLie,IT,charlie@yahoo.com,EMP103,7,charLie,
3,DAVID,ACCOUNTS,david@hotmail.com,EMP104,5,DAVID,
4,emma,HR,emma@gmail.com,EMP105,4,emma,
5,John Doe,IT,john.doe@gmail.com,EMP106,8,John,Doe
6,SARA ALI,ACCOUNTS,SARA@YAHOO.COM,EMP107,8,SARA,ALI
7,kevin joseph,SALES,kevin@gmail.com,EMP108,12,kevin,joseph
8,michael smith,MARKETING,michael@outlook.com,EMP109,13,michael,smith
9,ANNA,ACCOUNTS,ANNA@GMAIL.COM,EMP110,4,ANNA,

In [303]:
display(e_df["Employee"].str[:3], #slicing
        e_df["Employee"].str.slice(0,3) #slicing with slice fn
        )

0    ali
1    BOB
2    cha
3    DAV
4    emm
5    Joh
6    SAR
7    kev
8    mic
9    ANN
Name: Employee, dtype: object

0    ali
1    BOB
2    cha
3    DAV
4    emm
5    Joh
6    SAR
7    kev
8    mic
9    ANN
Name: Employee, dtype: object

In [304]:
e_df["Employee"].str.lower().str.count("a") #to count (use same case-upper/lower to ignore case)

0    1
1    0
2    1
3    1
4    1
5    0
6    3
7    0
8    1
9    2
Name: Employee, dtype: int64

In [305]:
e_df["Employee ID"].str.extract(r'(\d+)') #extract to get particular part of col as newcol (refer the code letters)

     0
0  101
1  102
2  103
3  104
4  105
5  106
6  107
7  108
8  109
9  110

In [306]:
e_df["Employee Info"]=e_df["Employee"].str.cat(e_df["Department"],sep=" - ") #concats text values inside column
e_df

,Employee,Department,Email,Employee ID,Length,First Name,Last Name,Employee Info
0,alice,ACCOUNTS,alice@gmail.com,EMP101,5,alice,,alice - ACCOUNTS
1,BOB,HR,BOB@GMAIL.COM,EMP102,3,BOB,,BOB - HR
2,charLie,IT,charlie@yahoo.com,EMP103,7,charLie,,charLie - IT
3,DAVID,ACCOUNTS,david@hotmail.com,EMP104,5,DAVID,,DAVID - ACCOUNTS
4,emma,HR,emma@gmail.com,EMP105,4,emma,,emma - HR
5,John Doe,IT,john.doe@gmail.com,EMP106,8,John,Doe,John Doe - IT
6,SARA ALI,ACCOUNTS,SARA@YAHOO.COM,EMP107,8,SARA,ALI,SARA ALI - ACCOUNTS
7,kevin joseph,SALES,kevin@gmail.com,EMP108,12,kevin,joseph,kevin joseph - SALES
8,michael smith,MARKETING,michael@outlook.com,EMP109,13,michael,smith,michael smith - MARKETING
9,ANNA,ACCOUNTS,ANNA@GMAIL.COM,EMP110,4,ANNA,,ANNA - ACCOUNTS

In [307]:
display(e_df["Employee"].str.split().str.get(0),e_df["Employee"].str.split().str.get(1)) #geting the element after splitting

0      alice
1        BOB
2    charLie
3      DAVID
4       emma
5       John
6       SARA
7      kevin
8    michael
9       ANNA
Name: Employee, dtype: object

0       NaN
1       NaN
2       NaN
3       NaN
4       NaN
5       Doe
6       ALI
7    joseph
8     smith
9       NaN
Name: Employee, dtype: object

## **Date & Time Handling**

### **Dataset**

In [308]:
import pandas as pd

orders_data = {
    "Order ID": [101,102,103,104,105,106],
    "Customer": ["Alice","Bob","Charlie","David","Emma","Frank"],
    "Order Date": [
        "2025-01-15",
        "2025-02-20",
        "2025-03-12",
        "2025-03-25",
        "2025-04-18",
        "2025-05-01"
    ],
    "Sales":[2500,1800,3200,1500,4100,2800]
}

orders_df = pd.DataFrame(orders_data)

orders_df
display(orders_df.info()) #it is a string not date

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Order ID    6 non-null      int64
 1   Customer    6 non-null      object
 2   Order Date  6 non-null      object
 3   Sales       6 non-null      int64
dtypes: int64(2), object(2)
memory usage: 324.0+ bytes

None

### **Code**

In [309]:
orders_df["Order Date"]=pd.to_datetime(orders_df["Order Date"]) #converted to date
orders_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Order ID    6 non-null      int64
 1   Customer    6 non-null      object
 2   Order Date  6 non-null      datetime64[ns]
 3   Sales       6 non-null      int64
dtypes: datetime64[ns](1), int64(2), object(1)
memory usage: 324.0+ bytes

In [310]:
orders_df["Year"]=orders_df["Order Date"].dt.year
orders_df

   Order ID Customer Order Date  Sales  Year
0       101    Alice 2025-01-15   2500  2025
1       102      Bob 2025-02-20   1800  2025
2       103  Charlie 2025-03-12   3200  2025
3       104    David 2025-03-25   1500  2025
4       105     Emma 2025-04-18   4100  2025
5       106    Frank 2025-05-01   2800  2025

In [311]:
orders_df["Month"]=orders_df["Order Date"].dt.month_name()
orders_df

   Order ID Customer Order Date  Sales  Year     Month
0       101    Alice 2025-01-15   2500  2025   January
1       102      Bob 2025-02-20   1800  2025  February
2       103  Charlie 2025-03-12   3200  2025     March
3       104    David 2025-03-25   1500  2025     March
4       105     Emma 2025-04-18   4100  2025     April
5       106    Frank 2025-05-01   2800  2025       May

In [312]:
orders_df["Day"]=orders_df["Order Date"].dt.day
orders_df

   Order ID Customer Order Date  Sales  Year     Month  Day
0       101    Alice 2025-01-15   2500  2025   January   15
1       102      Bob 2025-02-20   1800  2025  February   20
2       103  Charlie 2025-03-12   3200  2025     March   12
3       104    David 2025-03-25   1500  2025     March   25
4       105     Emma 2025-04-18   4100  2025     April   18
5       106    Frank 2025-05-01   2800  2025       May    1

In [313]:
orders_df["Weekday"]=orders_df["Order Date"].dt.day_name()
orders_df

   Order ID Customer Order Date  Sales  Year     Month  Day    Weekday
0       101    Alice 2025-01-15   2500  2025   January   15  Wednesday
1       102      Bob 2025-02-20   1800  2025  February   20   Thursday
2       103  Charlie 2025-03-12   3200  2025     March   12  Wednesday
3       104    David 2025-03-25   1500  2025     March   25    Tuesday
4       105     Emma 2025-04-18   4100  2025     April   18     Friday
5       106    Frank 2025-05-01   2800  2025       May    1   Thursday

In [314]:
orders_df["Order Date"][orders_df["Order Date"]>"2025-03-01"]

2   2025-03-12
3   2025-03-25
4   2025-04-18
5   2025-05-01
Name: Order Date, dtype: datetime64[ns]

In [315]:
orders_df["Order Date"][orders_df["Order Date"].dt.month==3] # can also use orders_df.loc returning order date at last

2   2025-03-12
3   2025-03-25
Name: Order Date, dtype: datetime64[ns]

In [316]:
orders_df["Quarter"]=orders_df["Order Date"].dt.quarter

In [317]:
orders_df["Is Weekend"]=(orders_df["Order Date"].dt.dayofweek>=5)
orders_df

,Order ID,Customer,Order Date,Sales,Year,Month,Day,Weekday,Quarter,Is Weekend
0,101,Alice,2025-01-15,2500,2025,January,15,Wednesday,1,False
1,102,Bob,2025-02-20,1800,2025,February,20,Thursday,1,False
2,103,Charlie,2025-03-12,3200,2025,March,12,Wednesday,1,False
3,104,David,2025-03-25,1500,2025,March,25,Tuesday,1,False
4,105,Emma,2025-04-18,4100,2025,April,18,Friday,2,False
5,106,Frank,2025-05-01,2800,2025,May,1,Thursday,2,False

In [318]:
orders_df["Delivery Date"] = [
    "2025-01-18",
    "2025-02-25",
    "2025-03-15",
    "2025-03-29",
    "2025-04-25",
    "2025-05-05"
]

orders_df["Delivery Date"]=pd.to_datetime(orders_df["Delivery Date"])

In [319]:
orders_df["Delivery Days"]=(orders_df["Delivery Date"]-orders_df["Order Date"]).dt.days

In [320]:
orders_df["Order Date"]=orders_df["Order Date"].dt.strftime("%d-%b-%Y") #string format to time

In [321]:
orders_df["Order Date"]=pd.to_datetime(orders_df["Order Date"])

orders_df.groupby(orders_df["Order Date"].dt.month_name())["Sales"].sum().sort_values(ascending=False)

Order Date
March       4700
April       4100
May         2800
January     2500
February    1800
Name: Sales, dtype: int64

## **map(), apply(), and lambda**

### map()

### **Dataset**

In [322]:
student_data = {
    "Student":["Ram","John","Sara","Emma","Alex"],
    "Gender":["M","M","F","F","M"],
    "Result":["P","F","P","P","F"]
}

student_df = pd.DataFrame(student_data)
student_df2 = student_df.copy() #because once it maps then old one is deleted

### **Code**

In [323]:
student_df2["Gender"]=student_df2["Gender"].map({"M":"Male","F":"Female"})

In [324]:
student_df2["Result"]=student_df2["Result"].map({"P":"Pass","F":"Fail"})

In [325]:
student_df2["Scholarship"]=student_df2["Result"].map({"Pass":"Eligible","Fail":"Not Eligible"})
student_df2

  Student  Gender Result   Scholarship
0     Ram    Male   Pass      Eligible
1    John    Male   Fail  Not Eligible
2    Sara  Female   Pass      Eligible
3    Emma  Female   Pass      Eligible
4    Alex    Male   Fail  Not Eligible

### apply()

### **Dataset**

In [326]:
# apply()

student_data = {
    "Student":["Ram","John","Sara","Emma","Alex"],
    "Marks":[95,72,35,88,40]
}

student_df = pd.DataFrame(student_data)

### **Code**

In [327]:
def result(Marks):
  if Marks >=40:
    return "Pass"
  else:
    return "Fail"

student_df["Result"]=student_df["Marks"].apply(result)
student_df

  Student  Marks Result
0     Ram     95   Pass
1    John     72   Pass
2    Sara     35   Fail
3    Emma     88   Pass
4    Alex     40   Pass

In [328]:
def grade(Marks):
  if Marks>=90:
    return "A"
  elif Marks >=75 and Marks<90:
    return "B"
  elif Marks>=40 and Marks<75:
    return "C"
  else:
    return "D"

student_df["Grade"]=student_df["Marks"].apply(grade)
student_df

  Student  Marks Result Grade
0     Ram     95   Pass     A
1    John     72   Pass     C
2    Sara     35   Fail     D
3    Emma     88   Pass     B
4    Alex     40   Pass     C

In [329]:
def b_mark(Marks):
  if Marks>=95: #capped to 100
    return 100
  else:
    return Marks+5

student_df["Bonus Marks"]=student_df["Marks"].apply(b_mark)
student_df

  Student  Marks Result Grade  Bonus Marks
0     Ram     95   Pass     A          100
1    John     72   Pass     C           77
2    Sara     35   Fail     D           40
3    Emma     88   Pass     B           93
4    Alex     40   Pass     C           45

### lambda

### **Code**

In [330]:
x=16

print("Value: ",(lambda x : x*2)(x))

print("Odd/Even: ",(lambda x:"Even" if x%2==0 else "Odd")(x))

print("Adult/Child: ",(lambda x: "Adult" if x>=18 else "Child")(x))

Value:  32
Odd/Even:  Even
Adult/Child:  Child

### apply() + lambda

### **Dataset**

In [331]:
student_data = {
    "Student":["Ram","John","Sara","Emma"],
    "Marks":[95,85,38,72],
    "Attendance":[92,60,95,80]
}

student_df = pd.DataFrame(student_data)

### **Code**

In [332]:
student_df["Double Marks"]=student_df["Marks"].apply(lambda x:x*2) #just for practice purpose
student_df

  Student  Marks  Attendance  Double Marks
0     Ram     95          92           190
1    John     85          60           170
2    Sara     38          95            76
3    Emma     72          80           144

In [333]:
student_df["Result"]=student_df["Marks"].apply(lambda x: "Pass" if x >=40 else "Fail")
student_df

  Student  Marks  Attendance  Double Marks Result
0     Ram     95          92           190   Pass
1    John     85          60           170   Pass
2    Sara     38          95            76   Fail
3    Emma     72          80           144   Pass

In [334]:
student_df["Bonus Marks"]=student_df["Marks"].apply(lambda x: 100 if x>=95 else x+5)
student_df

  Student  Marks  Attendance  Double Marks Result  Bonus Marks
0     Ram     95          92           190   Pass          100
1    John     85          60           170   Pass           90
2    Sara     38          95            76   Fail           43
3    Emma     72          80           144   Pass           77

In [335]:
student_df["Final Result"]=student_df.apply(lambda row:
                                            "Pass" if row["Marks"]>=40 and row["Attendance"]>=75
                                            else "Fail",
                                            axis=1 #row wise(0 for column)
                                            )
student_df

  Student  Marks  Attendance  Double Marks Result  Bonus Marks Final Result
0     Ram     95          92           190   Pass          100         Pass
1    John     85          60           170   Pass           90         Fail
2    Sara     38          95            76   Fail           43         Fail
3    Emma     72          80           144   Pass           77         Pass

In [336]:
student_df["Grade"]=student_df.apply(lambda row:
                                     "F" if row["Marks"]<40
                                     else
                                     "A" if row["Marks"]>=90 and  row["Attendance"]>=90
                                     else
                                     "B" if row["Marks"]>=75
                                     else "C",
                                     axis=1
                                     )
student_df

,Student,Marks,Attendance,Double Marks,Result,Bonus Marks,Final Result,Grade
0,Ram,95,92,190,Pass,100,Pass,A
1,John,85,60,170,Pass,90,Fail,B
2,Sara,38,95,76,Fail,43,Fail,F
3,Emma,72,80,144,Pass,77,Pass,C

## **Reading Data Sources (Reference-Not Workable)**

### **CSV**

In [ ]:
import pandas as pd

df=pd.read_csv("employees.csv")

In [ ]:
pd.read_csv("employees.csv",usecols=["Employee","Salary"]) #to use specific cols

In [ ]:
pd.read_csv("employees.csv",nrows=10) #to select n rows for testing

In [ ]:
pd.read_csv("employees.csv",skiprows=[1,2,3]) #to skip rows

In [ ]:
pd.read_csv("employees.csv",sep=";") #delimiter to ;

In [ ]:
pd.read_csv("employees.csv",index_col="Employee") #to make col(employee here) as index

In [ ]:
pd.read_csv("employees.csv",na_values=["NA","Missing","--"]) # to change misssing values to Nan

In [ ]:
df.to_csv("cleaned.csv", index=False) #to save as csv

### **Excel**

In [ ]:
df=pd.read_excel("employees.xlsx")

In [ ]:
pd.read_excel("employees.xlsx",sheet_name="Sales") #to select particular sheet name from workbook

pd.read_excel("employees.xlsx",sheet_name=1) #can also use col number

In [ ]:
pd.read_excel("employees.xlsx", usecols=["Employee","Salary"]) #to read selective cols

In [ ]:
pd.read_excel("employees.xlsx",nrows=10) #to read n rows

pd.read_excel("employees.xlsx",skiprows=10) #to skip rows

In [ ]:
df.to_excel("cleaned.xlsx",index=False) # to save as excel

### **SQL**

In [ ]:
from sqlalchemy import create_engine #to import sql lib

In [ ]:
engine=create_engine("database_connection_string") #to set up connection

In [ ]:
df=pd.read_sql("Select * from employees",engine) #to read all data

In [ ]:
querry="""select department, avg(salary) from employees group by department"""

df=pd.read_sql(querry,engine) #to read sql querry

In [ ]:
df.to_sql('employees',engine,if_exists='replace',index=False) #to save as sql(if exists - replace(fail,append))

## **Data Analysis Workflow**

1. CSV / Excel / SQL / API
2. Read into pandas
3. EDA
4. Cleaning
5. Analysis
6. Visualise
7. Export (CSV / Excel / SQL)